# .readthedocs.yaml
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"

# Install cachai and doc dependencies
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

# Sphinx config
sphinx:
  configuration: docs/source/conf.py